language: php
php:
  - 5.3
  #- 5.4
  #- hhvm
env:
  - WP_VERSION=latest WP_MULTISITE=0
  #- WP_VERSION=latest WP_MULTISITE=1
  #- WP_VERSION=3.8 WP_MULTISITE=0
  #- WP_VERSION=3.8 WP_MULTISITE=1
before_script:
  - bash bin/travis.sh wp_test root '' localhost $WP_VERSION
script:
  - mkdir -p build/logs
  - composer test
after_script:
  - php vendor/bin/coveralls -v
